### ISSUE TITLE
Lista de permisos?

### ISSUE THREAD

**Issue by U2ero** [Cadiducho/40ServidoresMC#13]
Hola!
Tengo una duda, cual es la lista de permisos? 

Saludos!

**Comment by Arhlex** [comment]
40servidores.recargar
40servidores.actualizar
40servidores.voto

**Comment by Cadiducho** [comment]
Toda la información de comandos se encuentra en la wiki, más concretamente aquí https://github.com/Cadiducho/40ServidoresMC/wiki/Comandos
