### ISSUE TITLE
Permisos plugin

### ISSUE THREAD

**Issue by MrPesee** [Cadiducho/40ServidoresMC#15]
¿Que permisos tengo que dar a mi users?
No tiene permisos para hacer /voter40

**Comment by Cadiducho** [comment]
"40servidores.voto" (Sin comillas, claro). Más información en https://github.com/Cadiducho/40ServidoresMC/wiki/Comandos#voto40 :D

**Comment by MrPesee** [comment]
Gracias, pero ahora mis usuarios tiene que entrar al enlace para votar, antes los admins hemos probado y lo ha hecho como actumaticamente, es esto asi?

**Comment by Cadiducho** [comment]
No. Debido a petición de los administradores de la web el plugin únicamente interpreta si se ha votado; cuándo, o si no; y a partir de ahí te da un premio si es el caso. En ningún momento el plugin realiza el voto, eso tiene que hacerse siempre vía web :+1:

**Comment by MrPesee** [comment]
Okey, muchas gracias!
