### ISSUE TITLE
Hacer compatible con otros plugins de votación

### ISSUE THREAD

**Issue by OscarGLorenz** [Cadiducho/40ServidoresMC#16]
Buenas, quiero sugerir que se haga compatible este plugin con otros plugins listeners de votaciones como:
http://dev.bukkit.org/bukkit-plugins/votifier/
https://www.spigotmc.org/resources/bungeevote.929/

**Comment by Cadiducho** [comment]
@ospa555 Estudiaré la posibilidad de enlazarlo con Votifier. Descarto la de BungeeVote (por el momento) dado que el plugin actual está preparado para servidor y no para proxy

**Comment by Cadiducho** [comment]
Quizás me equivoco, pero para enlazarlo con Votifier no es necesario agregar más cosas a la API de la Web?

**Comment by OscarGLorenz** [comment]
Para enlazarlo con votifier sin necesitar de un plugin intermediario realmente tendrías que rediseñar la api de la web. 

Cuando alguien vota en vez de guardarlo en una base de datos en vuestro servidor (supongo que es lo que haceis) y luego desde el juego usar el comando /vota40 que se limita a hacer esa petición a la web:
http://40servidoresmc.es/api2.php?nombre="+sender.getName()+"&clave="+plugin.getConfig().getString("clave")
Tendrías que hacer que al votar envie a un puerto del servidor al que se vota, el nombre usuario que vota encriptado con RSA que es en esencia como funcionan otras páginas de votaciones.
Lógicamente al registrar un servidor deberías pedir que te den su clave pública y el puerto que usan para recibir los votos, algunas páginas de lista de votaciones hacen un pequeño test para ver si funciona correctamente.

**Comment by Cadiducho** [comment]
Sí, incluye rediseño web. Eso no corresponde por mi parte, yo tengo unas herramientas bastantes limitadas para hacer el plugin (basicamente, una api html de lo más simple). Preguntaré a los 'superiores' y les llevaré esta idea

**Comment by OscarGLorenz** [comment]
Hoy acabo de añadir mi servidor a vuestra página, funciona a la perfección con BungeeVote

**Comment by MithrandirCraft** [comment]
Reabran este ticket. Es injusto que den el doble de puntos sin ni siquiera ofrecer la posibilidad de usar este plugin en bungee. Se que se ha encontrado una solución, pero no es la solución para todas las Networks (Para la nuestra no.)

O simplemente incorporen un sistema que contacte con votifier directamente en su web, asi nos ahorramos tener que instalar todo un plugin solo para contactar con vuestra web (Que es absurdo, para eso ya está Votifier).

**Comment by Cadiducho** [comment]
Buenas
Este repositorio es del plugin, no de la web en concreto. Entiendo tus molestias, pero yo no me puedo ocupar de eso. Contacta a través de la web que debe haber algo, yo solo puedo modificar el plugin.
Por cierto, no eres el primero que lo pides. En un futuro estará el plugin compatible para BungeeCord. Un saludo

**Comment by richicru** [comment]
Nuestro plugin se puede instalar en servidores dentro de bungee solo que la recompensa sólo premia una vez por voto y servidor. Podrán pedir la recompensa solo en uno de los servidores. Valen doble con nuestro plugin porque requiere una segunda acción de los jugadores y es más complicado de falsear.

**Comment by MithrandirCraft** [comment]
@Cadiducho Si involucra tu plugin, porque directamente estoy solicitando que ceseis el desarrollo y utilizeis Votifier xD, con el cual todo el mundo no tendría problemas con bungee, y no haría falta tener 2 comandos distintos para votar, que podría confundir a los jugadores.
No es limpio estar utilizando un sistema a parte mientras todos los servidores juegan con las reglas establecidas de Votifier. 2 comandos para hacer lo mismo, y 2 indicaciones a lo: "Hey, si quereis votar como en todas las paginas de voto, utilizad /vote! Pero para votar en la secta privada de 40MC voten así..."

Pero al parecer, no hay suficientes solicitudes sobre el tema, y parece ser que teneis algun temilla en la cabeza sobre seguridad, lo cual es respetable.

Se agradece que tengan en mente lo que les digo. Feliz navidad.
