### ISSUE TITLE
No funciona el Broadcast.

### ISSUE THREAD

**Issue by danielgarciagarcia** [Cadiducho/40ServidoresMC#17]
Pese a aparecer de forma predeterminada en la configuración, no parece que el plugin ejecute el broadcast debidamente. No al menos en mi servidor. He buscado por encima el uso aplicado de las variables "broadcast.activo" y "broadcast.mensajeBroadcast", pero no he encontrado nada. Sugiero introducir este fragmento de código a la clase VoteCMD, en el case que corresponde al voto efectuado correctamente.

` if (plugin.getConfig().getBoolean("broadcast.activado")) {
plugin.getServer().broadcastMessage(plugin.getConfig().getString("broadcast.mensajeBroadcast").replace("{0}", sender.getName()));}`

**Comment by Cadiducho** [comment]
Tienes razón. Probablemente lo perdí en alguna reescritura de código. Mañana lo miro más a fondo y lo arreglaré
