### ISSUE TITLE
Algunos errores y sugerencia

### ISSUE THREAD

**Issue by SliderKP** [Cadiducho/40ServidoresMC#18]
Todos mis usuarios no reciben recompensa automaticamente y tienen que tipear /vote40 después de votar, 

Sugerencia:
Agregar un top de votantes de cada servidor por lo menos para que se vea ingame.

Por otro lado muy bueno el sistema felicitaciones

**Comment by richicru** [comment]
El plugin funciona de esta forma porque al poner el comando se verifica que el voto es legal y además recibe el premio cuando lo desea.
Si quieres un top de votantes puedo darte una opción para añadirlo a tu web

**Comment by Cadiducho** [comment]
Con el comando /stats40 ya tienes las funcionalidades que pides (es solo para administración, en un principio). No un top como tal de quién ha votado más, pero sí los usuarios que votaron ese día
