### ISSUE TITLE
Error al escribir el comando /vote40

### ISSUE THREAD

**Issue by Mundo-Minecraft** [Cadiducho/40ServidoresMC#20]
Desde hace unas 2 semanas aprox, los usuarios me están reportando que al votar en la web y seguidamente escribir en el servidor /vote40 sale el siguiente mensaje:

[09:46:52] [Client thread/INFO]: [CHAT] &cHa ocurrido una excepción. Revisa la consola o avisa a un administrador

A partir de ahí, ya no les deja votar indica constantemente 

[Client thread/INFO]: [CHAT] [40ServidoresMC] No has votado hoy! Puedes hacerlo en http://40servidoresmc.es/servidor.php?cod=1923
 
Lo raro es que al rato vuelven a escribir el comando y funciona bien (no siempre) y en los logs solo sale esto.

[Server thread/ERROR]: [40ServidoresMC] &8[&b40ServidoresMC&8]

Al dia siguiente con el reinicio del servidor (se reinicia cada 24h) voan en la web seguidamente /vote40 y a veces se les repite el error y a veces vota bien... A mi por ejemplo nunca me ha salido este error, luego no veo que siga un patrón es algo un poco raro y un tanto aleatorio por lo que veo. Me temo que no puedo aportar mucha mas información.
Tengo la ultima versión de Spigot, y de los plugins que uso incluido este.

Gracias.

edito: tenia debug: false, lo activo e indicare que muestra.

**Comment by richicru** [comment]
Puede ser que en algunos momentos el servidor de 40servidoresmc.es esté sobrecargado de peticiones para validar votos. Por eso durante algunos segundos se rechazan las peticiones. Si el problema sigue quizá me plantee buscar un servidor más potente o que funcione por duplicado.

**Comment by Cadiducho** [comment]
Si al activar el debug sale algo más sería de gran ayuda, quizás así confirmamos si es un error del código, del servidor etc

**Comment by Mundo-Minecraft** [comment]
lamentablemente acabo de mirar ahora y si veo que ha fallado, pero solo muestra el error que indique arriba...

[Server thread/ERROR]: [40ServidoresMC] &8[&b40ServidoresMC&8]

De modo que no se mas deciros, lo único que puedo decir es que en estas 11 horas ha fallado a las 13:41, 16:23, 21:03, 21:46 hora española. Pero no indica nada mas en los logs.

**Comment by Cadiducho** [comment]
Es raro... según esta linea debería imprimir en consola el error en cuestión... https://github.com/Cadiducho/40ServidoresMC/blob/2.0/src/com/cadiducho/cservidoresmc/bukkit/cmd/VoteCMD.java#L64
Pero por lo que tú dices solo imprime el tag :S

**Comment by Mundo-Minecraft** [comment]
Pues si, lo estoy mirando y ahora mismo me acaba de salir a mi por primera vez. He puesto /vote40 se quedo pensando como 3 segundos y salio el mismo mensaje en el log. Y ahora ya no me deja votar, según me comentaron los jugadores con el reinicio del servidor o bien cuando deje volver a votar en la web vuelve a dejar escribir /vote40 o lo mismo falla de nuevo. Muy aleatorio.

[Server thread/ERROR]: [40ServidoresMC] &8[&b40ServidoresMC&8]

**Comment by MineServidorCraft** [comment]
Este error lo tengo en mi servidor, de vez en cuando. Me dice error por colores y solo aveces. Pones otra vez el comando y funciona otra vez. No sé porque pasa esto. Pero me está pasando desde hace unos 5-7 dias. Los dos meses anteriores nada.

**Comment by Mundo-Minecraft** [comment]
A mi parecido, a veces deja volver a poner el comando y otras ya no deja mas. No puedo aportar mas información como comente, ya que he seguido revisando logs pero no da mas info.

**Comment by Cadiducho** [comment]
El error que saltaba de vez en cuando debería estar solucionado en la próxima versión, en #22 se consiguió aportar algo más de información
