### ISSUE TITLE
Plugin hace que servidor deje de funcionar

### ISSUE THREAD

**Issue by ipozow** [Cadiducho/40ServidoresMC#22]
Ayer tuve que sacar el plugin porque hacía que el servidor se reiniciara a cada rato. Nunca había pasado antes. 
Aquí está el error: https://pastebin.com/UXqEQ9MW

Igual, la recompensa da un poco de lag. Cada vez que los jugadores usan /voto40 da un poco de lag, y si muchos lo usan da un lag fuerte.

**Comment by ipozow** [comment]
El LagMonitor deja un mensaje en la consola con un error que podría ayudar al desarrollador a encontrar el problema. ¿Lo envío?

**Comment by Cadiducho** [comment]
Envía todo lo que creas que puede ayudarme, me viene perfecto

**Comment by ipozow** [comment]
https://pastebin.com/3CivDmKK

**Comment by Cadiducho** [comment]
Según parece esto fue debido a que la web estuvo caída unos minutos, el plugin no pudo consultar y este colapsó.
Lo de la web es algo poco habitual, pero es cierto que puede pasar, así que voy a subir un parche *intentando* arreglar esas caídas y algún que otro retoque más

**Comment by Cadiducho** [comment]
Closed in b9741aeeb94a1a6b0ad02133a72523e867b8f50d
