### ISSUE TITLE
no me aprece la clave

### ISSUE THREAD

**Issue by dino2045** [Cadiducho/40ServidoresMC#24]
hola señores estoy confundido no me aparece la key osea la clave de la llave para conectar mi server con votes40 
Servidor de: Uruguay PlanetCub [ #0 ] ★★★★★ [1] [Pendiente de revisión]
me dise no entiedo que aser me explica gracias

**Comment by Cadiducho** [comment]
La clave te debería aparecer en el menú de la web, cuando inicias sesión. Al salir que está pendiende de revisión, igual es que aún no se te ha generado la clave en ese punto.
¿lo has logrado ya?
