### ISSUE TITLE
Problema con el plugin 40svmc y PaperSpigot

### ISSUE THREAD

**Issue by JuanDouCore** [Cadiducho/40ServidoresMC#26]
Resulta que cambie la build de mi servidor a PaperSpigot. Y cuando empezo a funcionar el plugin de 40servidores empezo a funcionar mal. No daba el último comando de la lista de premios y tampoco daba el broadcast sobre que había votado. Algun error?

**Comment by Cadiducho** [comment]
Hola,
no he probado las nuevas versiones del plugin en PaperSpigot, así que necesitaré unos cuántos datos más que puedas proporcionarme.
¿Qué versión de PaperSpigot y de Minecraft usas?
¿Tienes actualizado el plugin a la última versión?
Cuando ejecutas los comandos y, por ejemplo, no daba el broadcast, ¿la configuración estaba bien puesta? ¿salía algo por consola?

**Comment by Cadiducho** [comment]
Cierro por falta de información al respecto
