### ISSUE TITLE
Demasiado consumo por parte del comando /vote40

### ISSUE THREAD

**Issue by JuanDouCore** [Cadiducho/40ServidoresMC#27]
![sin titulo](https://user-images.githubusercontent.com/22947314/44959907-d8e13780-aecc-11e8-899a-2c03b5da84e1.png)
Ahí en la foto se puede ver claramente todo lo que consume el plugin cada vez que se coloca el comando /vote40. No puede ser que tenga un lag spike cada vez que se ejecuta ese comando. Se necesita una optimización..

**Comment by Cadiducho** [comment]
¿Qué versión del plugin estás usando? En la más actual se reescribió todo ese código porque como bien dices, no podía ser que hubiese un lag spike cada vez que ejecutas el comando, y en teoría ahora funcionaba mejor

**Comment by Cadiducho** [comment]
Cierro debido a que no he podido reproducir el error ni he obtenido más respuesta
