### ISSUE TITLE
Error al ejecutar /vote40

### ISSUE THREAD

**Issue by sOxTw** [Cadiducho/40ServidoresMC#28]
Estoy teniendo un error al ejecutar el comando /vote40 o sus alias.
El error es el siguiente:
[Server thread/ERROR]: [40ServidoresMC] &8[&b40ServidoresMC&8]

Podrían ayudarme?

**Comment by Cadiducho** [comment]
¿no hay nada más del error?

**Comment by sOxTw** [comment]
No, nada más. Al usar el comando. En el chat dice algo como "ha ocurrido una excepción. Dar aviso al administrador del servidor."
Te hago una consulta, estamos bloqueando países por la razón del Anti-Ddos y de Bots. ¿Podría ser esto? Y si esta es la razón. Habría alguna forma de obtener los puertos de conección que usa el plugin para darle "allow" a la protección de mi servidor y que la conexión sea limpia?

**Comment by Cadiducho** [comment]
Me sorprendería, pero podría ser... cosas más raras he visto. He de hacer unas pruebas al respecto de eso.
¿fallan todas las conexiones? O solo algunas

Edit: ¿las claves del servidor en la configuración están bien puestas?

**Comment by sOxTw** [comment]
Ya logramos reparar el comando. 
Te comento, usamos iptable para bloquear países, así evitamos los ataques de boots con proxy libre.

Le dimos allow a la IP de la web de los 40ServidoresMC y el comando volvió a funcionar. Pero si miramos la lista de servidores en 40ServidoresMC aparecemos OFFLINE. Seguramente sea algún puerto o IP que requiere hacer PING al servidor para mostrar esa información. Me podrías ayudar con eso?

La clave si esta correctamente colocada, es mas la corregí 2 veces pensando que era eso.

En resumen lo único que falla ahora es que aparecemos como OFFLINE la web.

**Comment by Cadiducho** [comment]
Habiendo permitido la IP de la web, yo imagino que el puerto que usa para hacer ping es el 25565, pero la verdad es que no te se decir concretamente cosas internas sobre la web

**Comment by Cadiducho** [comment]
Creo que el servidor que actualiza los usuarios online y demás tiene la IP 213.251.182.111 
Prueba a añadir las reglas correspondientes a estas

**Comment by sOxTw** [comment]
Estamos realizando la prueba a ver si soluciona el problema. Muchas gracias, Te aviso en un rato.

**Comment by sOxTw** [comment]
Por si a alguien le pasa lo mismo. Aclaro que le dimos allow a las siguientes IPs
IP de la WEB: 87.98.231.40
IP de consulta: 213.251.182.111

Y con eso ya lo solucionamos.

Muchas gracias @Cadiducho !

**Problema Solucionado ~**
