### ISSUE TITLE
Error de SSL al establecer conexiones a la web

### ISSUE THREAD

**Issue by MTXecron** [Cadiducho/40ServidoresMC#29]
AÑADO LA CLAVE DE MI SERVIDOR PONGO LA URL DEL VOTE Y NO DA NADA,NOSE SI NECESITA OTRO PL APARTE PARA SU FUNCIONAMIENTO ESPERO RESPUESTA PORFAVOR!

**Comment by Cadiducho** [comment]
a qué te refieres con que no da nada? qué comandos has probado?

**Comment by MTXecron** [comment]
El server es mineteam, creo que hsblo contigo el otro owner por telegram,y
el error es que la config, pongo la clave y los comandos de los premios que
debe dar, pero al votar no te da nads y sale un msg de contactar a un
admin, pues al escribir /test40 me da los premios, es algo que no entiendo

**Comment by Cadiducho** [comment]
Probad esta versión (el archivo .jar que dice 2.4.1) y moved los dos archivos con extensión .der a la carpeta plugins/40ServidoresMC (donde se encuentra la config), por favor. 
Debería estar solventado
[plugin prueba.zip](https://github.com/Cadiducho/40ServidoresMC/files/2522273/plugin.prueba.zip)

**Comment by Cadiducho** [comment]
Modifico el nombre de la issue y dejo este link como referencia por si más gente tiene el error

Referencias para encotrar el error si se busca
_javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target_

**Comment by Cadiducho** [comment]
El parche que subí en la versión anterior está actualizado para la versión 2.5. 
Dado que no me respondisteis, no sé si lo seguíais necesitando o no, sea como fuere la publico por si acaso.

Lo más probable es que esta sea la última versión del plugin con ese parche, pues Java 8_101 salió ya hace 3 años, y lo normal es que vuestro hosting tienda a actualizar a la versión 181 o 201 y superiores, donde este error de certificados SSL ya no existe.
