### ISSUE TITLE
Doble recompenza

### ISSUE THREAD

**Issue by sOxTw** [Cadiducho/40ServidoresMC#30]
La verdad no hay error pero si mis Staffs me lo reportaron. 
Te comento, usas /vote40, vas a la pagina y realizas el vote.
Cuando vas a reclamar la recompensa das doble comando lo mas rápido posible y te entrega el doble de recompensa (2 veces)

**Comment by sOxTw** [comment]
Te comento otra cosa? es posible meterle un tiempo de espera para ejecutar el proximo comando? es decir 10 segundos por cada /vote40

**Comment by Cadiducho** [comment]
Es posible y además creo que es la mejor solución a lo que planteas. Si por lo que sea, la web no actualiza instantáneamente el estado del voto y puede recibir dos peticiones "simultáneas" del mismo voto, con un simple cooldown se solucionaría.
A 10 segundos como planteas, o por qué no a 30 o 60

**Comment by sOxTw** [comment]
Si sería genial un cooldown hasta de 10 minutos. 
Otra sugerencia sería agregar alias al comando si es posible /vote porque mucha gente lo conoce así y no sabe de /vote40. Pero eso ya sería mucho pedir jajaja. Con el cooldown sería genial.

**Comment by sOxTw** [comment]
Te comento algo, Existe un mod que te permite ejecutar comandos o texto en chat con solo precionar una tecla, Eso produce el bug, si o si necesitamos cooldown.

`[14:21:46] [Server thread/INFO]: Sr_kuartuke issued server command: /vote40  `
`[14:21:46] [Server thread/INFO]: Sr_kuartuke issued server command: /vote40  `
`[14:21:46] [Server thread/INFO]: Sr_kuartuke issued server command: /vote40  `
`[14:21:46] [Server thread/INFO]: Sr_kuartuke issued server command: /vote40  `
`[14:21:46] [Server thread/INFO]: Sr_kuartuke issued server command: /vote40  `
`[14:21:46] [Server thread/INFO]: CONSOLE issued server command: /eco give Sr_kuartuke 500  `
`[14:21:46] [Server thread/INFO]: $500 han sidos agregados a la cuenta de [Moderador]Sr_kuartuke Nuevo presupuesto: $17147  `
`[14:21:46] [Server thread/INFO]: Gracias a Sr_kuartuke por votarnos! El ya ha obtenido su recompensa, usa /vote40 y obten el tuyo.  `
`[14:21:46] [Server thread/INFO]: CONSOLE issued server command: /eco give Sr_kuartuke 500  `
`[14:21:46] [Server thread/INFO]: $500 han sidos agregados a la cuenta de [Moderador]Sr_kuartuke Nuevo presupuesto: $17647  `
`[14:21:46] [Server thread/INFO]: Gracias a Sr_kuartuke por votarnos! El ya ha obtenido su recompensa, usa /vote40 y obten el tuyo.  `
`[14:21:46] [Server thread/INFO]: CONSOLE issued server command: /eco give Sr_kuartuke 500  `
`[14:21:46] [Server thread/INFO]: $500 han sidos agregados a la cuenta de [Moderador]Sr_kuartuke Nuevo presupuesto: $18147  `
`[14:21:46] [Server thread/INFO]: Gracias a Sr_kuartuke por votarnos! El ya ha obtenido su recompensa, usa /vote40 y obten el tuyo.  `
`[14:21:46] [Server thread/INFO]: CONSOLE issued server command: /eco give Sr_kuartuke 500  `
`[14:21:46] [Server thread/INFO]: $500 han sidos agregados a la cuenta de [Moderador]Sr_kuartuke Nuevo presupuesto: $18647  `
`[14:21:46] [Server thread/INFO]: Gracias a Sr_kuartuke por votarnos! El ya ha obtenido su recompensa, usa /vote40 y obten el tuyo.`

puedes ver en estos logs, un moderador me mostró como se hace. Mientras mas rápido eres presionando la tecla mas recompensa obtienes. El cooldown debería ser el mismo tiempo de refresco de la web. Asi no habria forma de bugearlo.

Gracias por leerme.

**Comment by Cadiducho** [comment]
Bueno, la solución -por suerte- es fácil con ese cooldown.
Intento tener la versión lista para este fin de semana, pero tampoco lo prometo

**Comment by sOxTw** [comment]
Perfecto, lo antes posible mejor,  esperare hasta que la tengas lista no hay problema. por ahora intentaremos colocarle cooldown con un plugin externo.

**Comment by Cadiducho** [comment]
Está ya subido el cooldown con unos cuantos arreglos más del plugin. Gracias por reportar el error!

**Comment by sOxTw** [comment]
Estaremos probando la nueva versión, cualquier cosita te aviso. Muchas gracias.
