### ISSUE TITLE
Mensajes quincenales

### ISSUE THREAD

**Issue by MithrandirCraft** [Cadiducho/40ServidoresMC#32]
Hola. Habés dejado de enviar las estadisticas quincenales por correo?
No recibo esos correos desde hace aproximadamente un mes.

**Comment by richicru** [comment]
Mira el correo no deseado. Si quieres preguntar algo estamos en twitter @40servidoresmc

**Comment by MithrandirCraft** [comment]
![imagen](https://user-images.githubusercontent.com/6623704/62732216-1c6ceb80-ba24-11e9-9333-d070429773bc.png)

Y no recibo correos. En ninguna bandeja.
