### ISSUE TITLE
Redirección errornea con el botón de discord

### ISSUE THREAD

**Issue by MithrandirCraft** [Cadiducho/40ServidoresMC#35]
Por alguna extraña razón, cuando clickas el botón de enlace al discord de un servidor en el listado de 40smc, te enlaza con una
imagen de imgur que promociona la IP de un servidor random.

Pruebenlo ustedes mismos:
![imagen](https://user-images.githubusercontent.com/6623704/89739705-49167180-da83-11ea-9dcf-73c5960b5d2a.png)

La imagen en cuestión es esta: https://imgur.com/J8ItZf5

**Comment by richicru** [comment]
Ya he solucionado el problema. Era un error en el código de la web.
De todas formas los problemas con la web envíalos a @40servidoresmc o por email. 
Esto es solo para el plugin de recompensa de votos
