### ISSUE TITLE
Duda

### ISSUE THREAD

**Issue by Bandy22600** [Cadiducho/40ServidoresMC#37]
hola, buenas noches, disculpen tengo una duda y espero alguien me pueda ayudar, quiero dar como recompensa una llave del crazy creates, al votan vote40 solo que no se cual sea el comando que tengo que poner, ayuda por favor, se los agradecería mucho :smile:

**Comment by 4drian3d** [comment]
Este repositorio es sobre temas del plugin 40ServidoresMC, el plugin ejecuta el comando, tu debes saber el comando del plugin para agregarlo a la configuración.

**Comment by Cadiducho** [comment]
Te digo lo mismo que @4drian3d, este plugin lo puedes configurar para que ejecute cualquier comando cuando un usuario reciba su recompensa. Literalmente, cualquiera. Podrías poner que cuando alguien vote se le banee si así lo deseas...
Siendo así, tienes que saber qué comando crea el objeto llave de la que hablas, y luego poner ese comando en la configuración. Yo, personalmente, no sé qué plugin es ese así que no te puedo ayudar. Tampoco creo que sea el lugar

Cierro la issue ya que no es nada relacionado a este plugin. Siento si no te he ayudado lo suficiente
