### ISSUE TITLE
error con los votos

### ISSUE THREAD

**Issue by SliderKP** [Cadiducho/40ServidoresMC#38]
[15:08:02 ERROR]: [40ServidoresMC] Excepción intentando votar: java.net.SocketTimeoutException: Read timed out

**Comment by Cadiducho** [comment]
Hola, puedes detallar más? En qué circunstancias te ha ocurrido eso?

**Comment by SliderKP** [comment]
Buenas noches, el problema ocurrio de un momento a otro, pero horas despues se soluciono solo, por lo cual supuse que habia sido un problema de 40servidoresmc.

De todas maneras gracias por tu respuesta.
