### ISSUE TITLE
problemas con el comando /vote40

### ISSUE THREAD

**Issue by julion12** [Cadiducho/40ServidoresMC#39]
hola,  todos marchaba bien hasta esta mañana en el servidor pero hace una hora el comando /vote 40 empezo a presentar error me sale a ocurrido una excepcion, avisa a un administrador, eso sale cuando los jugadores intentar acceder al comando, ya revise el key y todo la configuracion esta bien porque estaba funcionando perfectamente

**Comment by Cadiducho** [comment]
Hola, se mostraba algún tipo de error en la consola además del mensaje de alerta a los usuarios? Podrías compartir ese error?

**Comment by Cadiducho** [comment]
Cierro porque no se ha vuelto a saber nada de esto
