### ISSUE TITLE
Como subir cambios al repositorio

### ISSUE THREAD

**Issue by apatuka** [Cadiducho/40ServidoresMC#40]
Buenas, he agregado un evento que se dispara cuando alguien vota. Y me gustaria subirlo para que se pueda usar para otros plugins.

**Comment by Cadiducho** [comment]
hola! Para sugerir cambios al repositorio tienes primero que hacer un fork, realizar tus cambios en tu repositorio clonado y posteriormente hacer una solicitud de fusión de tu código en el de este repositorio, lo que se llama hacer un pull-request. Una vez tengas los cambios en tu repositorio, la propia página de github te debería mostrar los botones adecuados para hacerlos sin mucho problema, si es que estás algo perdido en el proceso.

Gracias por aportar algo :)

**Comment by apatuka** [comment]
Va el PR, seguimos allí ante cualquier observación que encuentres. Un saludo.
