### ISSUE TITLE
Sugerencia

### ISSUE THREAD

**Issue by TH3N3WN00B** [Cadiducho/40ServidoresMC#42]
Mi sugerencia es un poco mas dificil de hacer, pero necesaria de cierta forma:

Que el plugin pueda ejecutar comandos como OP o como Consola, para que mas plugins puedan dar los regalos por votar

Ej:

- OP: crazycrates give physical [nombre de llave] 1 {0}
- CONSOLE: crazycrates give physical [nombre de llave] 1 {0}

**Comment by Cadiducho** [comment]
Hola! El plugin siempre ejecuta los comandos como Consola (por lo tanto con los permisos de OP).
Lo que sería más complicado de hacer sería que lo ejecutase simulando que ha sido un administrador el que ha invocado el comando, pues dependería de que este usuario administrador estuviese también conectado etc.
Justamente lo que pides es como ya funciona

**Comment by TH3N3WN00B** [comment]
Perfecto, eso era lo que estaba buscando!
