### ISSUE TITLE
Error con el comando /vote40

### ISSUE THREAD

**Issue by AndreGR2024** [Cadiducho/40ServidoresMC#43]
Hola, hace unos días me salió este errror:  "Ha ocurrido una excepción. Avisa a un administrador."
Revisé la consola y vi esto: [16:51:21 ERROR]: [40ServidoresMC] Excepción intentando votar: Unexpected character (<) at position 0.
La key está bien puesta, versión del plugin 2.5, necesito que me ayuden gracias

**Comment by matipoirierg** [comment]
> Hola, hace unos días me salió este errror: "Ha ocurrido una excepción. Avisa a un administrador." Revisé la consola y vi esto: [16:51:21 ERROR]: [40ServidoresMC] Excepción intentando votar: Unexpected character (<) at position 0. La key está bien puesta, versión del plugin 2.5, necesito que me ayuden gracias

mismo error, asumo que ahora mismo simplemente hay un problema con la api que está usando 40servidoresmc, apenas arregluen eso el plugin funcionara bien otra vez sin actualización.

**Comment by richicru** [comment]
Efectivamente. El servidor estaba en modo desarrollo para hacer unos arreglos y ya está solucionado.
