### ISSUE TITLE
Compra de Inscripción premium

### ISSUE THREAD

**Issue by Loowop** [Cadiducho/40ServidoresMC#45]
Más que problema es una consulta, solo que desde el foro de la web no me deja iniciar sesión para ponerla y la mande por Contacto pero no me han dado respuesta y en verdad estoy muy interesado.

En el apartado de premium dice "La verificación de datos será al momento y tendrás tu servidor funcionando al 100% en la web".

Mi duda es, eso se refiere a que pese al pago aun tendría que cumplir los criterios de calidad? Pregunto porque estoy desarrollando apenas una network y estoy por terminar mi survival que es donde implementaré el plugin y si bien tengo algo de jugadores, no se si suficiente para cumplir ese criterio.

El pago salta los criterios o solo salta la lista de espera a la verificación?

**Comment by richicru** [comment]
No hay criterio de mínimo de jugadores en 40servidoresMC. Si pagas el registro VIP puedes registrar el servidor sin problemas y sin esperas. Si quieres esperar que haya huecos libres tendrías que ir viendo la web. Cada 3 días borramos servidores inactivos (si hay alguno)

**Comment by Loowop** [comment]
> No hay criterio de mínimo de jugadores en 40servidoresMC. Si pagas el registro VIP puedes registrar el servidor sin problemas y sin esperas. Si quieres esperar que haya huecos libres tendrías que ir viendo la web. Cada 3 días borramos servidores inactivos (si hay alguno)

Adicional 2 dudas, al momento del registro de datos, dichos datos a posteriori se pueden editar? hay cuestiones como pagina web o cuenta de twitter personal del servidor que aun no tenemos pero se planea tener a futuro y como dice que poner datos erróneos conlleva a sancion, no se si eso incluya dejar partes en blanco o para después.

Adicional la ip publica tiene que ser la numeral la del server.properties? o puedo poner el subdominio?
