### ISSUE TITLE
Duda sobre llenado de datos inscripción premium.

### ISSUE THREAD

**Issue by Loowop** [Cadiducho/40ServidoresMC#46]
Hay cuestiones como pagina web o cuenta de twitter personal del servidor que aun no tenemos pero se planea tener a futuro y como dice que poner datos erróneos conlleva a sanción, no se si eso incluya dejar partes en blanco o para después.

Al momento del registro de datos, dichos datos a posteriori se pueden editar/agregar? 

Adicional la ip publica tiene que ser la numeral la del server.properties? o puedo poner el subdominio?

**Comment by richicru** [comment]
Hola. Actualmente es obligatorio tener una cuenta de twitter vinculada al servidor. Crearla es gratuito y puedes asociarla a un gmail gratuito también.

Lo de los datos erróneos es porque hay servidores que intentan poner modos de juego que no tienen. Si tienes datos vacíos o "de menos" no hay problema.

Tras el registro VIP e iniciando sesión con la cuenta de twitter vinculada podrás editar tus datos sin problema. 

La IP pública es la ip que mostramos en nuestra web. La IPREAL es el campo que usamos para hacer ping al servidor. A veces, por seguridad los servidores ponen una IP diferente para que podamos hacer ping y ver si el servidor está online saltando las protecciones del firewall o plugins.
