### ISSUE TITLE
Error vote 40

### ISSUE THREAD

**Issue by Drihuxd** [Cadiducho/40ServidoresMC#47]
Al ejecutar el comando vote40 o similares y votar en la pagina me sigue enviando el mensaje de votar incluso despues de haberlo hecho, igualmente al ejecutar el comando stats40 me sale el error en la consola
[20:16:49 ERROR]: [40ServidoresMC] Excepción obteniendo estadisticas: null
Servidor ejecutado con purpur 1.18.2

Si necesitan mas informacion no duden en preguntar.

**Comment by Cadiducho** [comment]
Hola, sin más datos es complicado saber
Lo más probable es que esté mal configurada la clave de tu servidor en el archivo config.yml. ¿Puedes verificar eso?

**Comment by Cadiducho** [comment]
Cierro al no tener más información
