### ISSUE TITLE
No se detecta el servidor online

### ISSUE THREAD

**Issue by Santurde99** [Cadiducho/40ServidoresMC#48]
Hola, tenemos el siguiente problema y creemos que puede estar relacionado con el plugin.

En la web de los 40 de nuestro servidor lleva algunas semanas saliendo como offline pese a estar online, sin embargo, los votos se procesan correctamente y son contabilizados. Los 40 es la única pagina de votos con la que tenemos este problema y hemos revisado todo, el puerto, la clave que se nos da en la web y no encontramos nada.

También añadir que al usar el comando de stats40 que provee el plugin da un error "null" por la consola, mientras que el resto de comandos del plugin funcionan correctamente

El servidor es paper 1.19.4, he activado el modo debug del plugin pero no he notado nada en los logs de la consola, asique, cualquier cosa que pueda aportar para solucionar el problema pídanmela y lo adjunto.

**Comment by Cadiducho** [comment]
Hola! Sobre lo de que salga como offline creo que @richicru podrá ayudarte más, le menciono para que lo lea.

Sobre lo del /stats40 me llama la atención que el resto de comandos funcionen y este no (sobre todo, que los votos sean contabilizados correctamente pero a la vez no te devuelva estadísticas). No sé si tendrá algo que ver con que la web, al detectar el servidor como apagado, de una respuesta incorrecta y el plugin falle escribiendo null por eso.
Lo único que se me ocurre para echarte una mano es que me envíes por privado la clave de tu servidor, para comprobar exactamente qué está ocurriendo y poder reproducir yo el problema. 
Por favor, no respondas al issue con tu clave, que es privada.
Si te parece bien, puedes escribirme al mail cadiducho@gmail.com o por Telegram https://telegram.me/Cadiducho

**Comment by Santurde99** [comment]
Acabo de enviarte la clave por correo, si hay alguna cosa más que pueda aportar, pídanmela.

**Comment by Cadiducho** [comment]
Hola, tras probar con tu clave puedo confirmar que es un error de la API. Por lo que sea, la web en lugar de devolver las estadísticas u algún otro dato relevante, dice que Error en petición y ahí se queda.
No es cosa del plugin y creo que no hay nada que pueda hacer yo, porque yo no puedo modificar nada de la web. Vuelvo a mencionar a @richicru a ver si te puede ayudar

**Comment by Santurde99** [comment]
Muchas gracias por tu tiempo, a ver si richicru lo ve y puede echarnos una mano porque se acerca la fecha limite de que nos quiten el server de la web y hemos probado todas las vías de contacto (foro, email y twitter)y ninguna ha servido.

**Comment by Cadiducho** [comment]
El problema del comando de estadísticas ya está solucionado 
No tengo información sobre que el servidor salga offline, ni puedo arreglarlo pues solamente me ocupo de este plugin y no nada de la web. Lo siento
